steps:
  - script: |
      conda config --add channels conda-forge
      conda config --set always_yes true
      conda config --set quiet true
    displayName: Configure conda
  
  - script: |
      conda install conda-build conda-verify pip
      conda clean --all
      python -m pip install --upgrade pip
      conda build --version
    displayName: Install conda-build dependencies
    
  - script: |
      export PYTHONUNBUFFERED=1
      conda build tools/conda-recipe
    displayName: 'Build and test'
