jobs:
  - job: 'Linux'
    pool:
      vmImage: 'ubuntu-latest'
    timeoutInMinutes: 360

    strategy:
      matrix:
        Python39:
          CONDA_PY: '3.9'
          CONDA_NPY: '1.21'
        Python310:
          CONDA_PY: '3.10'
          CONDA_NPY: '1.21'
        Python311:
          CONDA_PY: '3.11'
          CONDA_NPY: '1.24'

      maxParallel: 10

    steps:
      - template: checkout.yml
      - bash: echo "##vso[task.prependpath]$CONDA/bin"
        displayName: Add conda to PATH

      - bash: sudo install -d -m 0777 /usr/envs
        displayName: Fix Conda permissions

      - template: conda-setup+build.yml
