jobs:
  - job:
    displayName: "OS X"
    pool:
      vmImage: 'macOS-latest'
    timeoutInMinutes: 360

    strategy:
      matrix:
        Python39:
          CONDA_PY: '3.9'
          CONDA_NPY: '1.21'
        Python310:
          CONDA_PY: '3.10'
          CONDA_NPY: '1.21'
        Python311:
          CONDA_PY: '3.11'
          CONDA_NPY: '1.24'

    steps:
      - template: checkout.yml
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '$(CONDA_PY)'
        displayName: Use Python $(CONDA_PY)
      
      - script: |
          curl -L https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -o miniconda.sh
          bash miniconda.sh -b -p $HOME/miniconda
          export PATH="$HOME/miniconda/bin:$PATH"
          echo "##vso[task.prependpath]$HOME/miniconda/bin"
        displayName: Install Miniconda

      - template: conda-setup+build.yml
